messages:
  permission: '&8(&6&oLektvary&8) &7Na tohle nemáš práva.'
  arguments: '&8(&6&oLektvary&8) &7Špatné použití argumentů.'
  give: '&8(&6&oLektvary&8) &7Bylo přidáno &6&o{AMOUNT}x &7lektvarů &6&o{POTION} &7hráči &6&o{PLAYER}&7.'
  giveTarget: '&8(&6&oLektvary&8) &7Získal jsi &6&o{AMOUNT}x &7lektvarů &6&o{POTION}&7.'
  potionDoesntExists: '&8(&6&oLektvary&8) &7Tento lektvar neexistuje.'
  playerIsOffline: '&8(&6&oLektvary&8) &7Hráč &6&o{PLAYER} &7je offline.'
potions:
  hornik:
    type: SPEED
    name: '&8(&6&oHorníkův lektvar&8)'
    lore:
      - '&7S tímto lektvarem budeš'
      - '&7kopat jako ďas 10 minut.'
    effects:
      - 'fast_digging;1;600'
      - 'night_vision;0;600'
  rytir:
    name: '&8(&6&oRytířův lektvar&8)'
    lore:
      - '&7S tímto lektvarem budeš kopat jako ďas 10 minut.'
    effects:
      - 'INCREASE_DAMAGE;1;600'
      - 'speed;0;600'
